### ISSUE TITLE
Upload sketch error

### ISSUE THREAD

**Issue by t3ch9** [imchin/ROS2_markSerial#3]
When I try to upload sketch 'example_publish.ino' to Arduino, I get the following error:

/home/ubuntu/mark_serial_ws/src/Arduino_example/example_publish/example_publish.ino: In function 'void loop()':
example_publish:15:32: error: no matching function for call to 'MarkSerial::publish_Pose(float&, float&, float&)'
   ros2Serial.publish_Pose(x,y,z);   //publish topic Pose (x,y,z,...,...) sort by Pose.msg
                                ^
In file included from /home/ubuntu/mark_serial_ws/src/Arduino_example/example_publish/example_publish.ino:1:0:
/home/ubuntu/arduino-1.8.19/libraries/MarkSerial/MarkSerial.h:16:14: note: candidate: void MarkSerial::publish_Pose(String, float, float)
         uint8_t _stop[2]={126,126};
              ^~~~~~~~~~~~
/home/ubuntu/arduino-1.8.19/libraries/MarkSerial/MarkSerial.h:16:14: note:   no known conversion for argument 1 from 'float' to 'String'
exit status 1
IntelliSense configuration already up to date. To manually rebuild your IntelliSense configuration run "Ctrl+Alt+I"
[Error] Uploading sketch 'src/Arduino_example/example_publish/example_publish.ino': Exit with code=1

**Comment by imchin** [comment]
In the old version of Pose.msg, it contained [float x ,float y , float z], but in this version, it contains [string x , float y ,float z].
But you can customize interface file xxx.msg in the markserial_interfaces package.
 
Now I have a new package. Xicro can publish and subscribe. However, Xirco is still in development. In the future, Xicro will be able to use service and action and will also be compatible with Arduino, esp and SM32.

https://github.com/imchin/Xicro

**Comment by t3ch9** [comment]
Thank you, will check the new package Xicro.
